version: '3.8'

services:

  rabota-mongo-dev:
    image: mongo
    container_name: rabota-mongo-dev
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEV_ROOT_USERNAME?Variable not set}
      MONGO_INITDB_ROOT_PASSWORD: ${DEV_ROOT_PASSWORD?Variable not set}
      MONGO_INITDB_DATABASE: dev-db
    volumes:
      - rabota-mongo-dev-data:/data/db
    networks:
      - rabota-dev-api-network

  rabota-mongo-express-dev:
    image: mongo-express
    container_name: rabota-mongo-express
    restart: unless-stopped
    env_file: .env
    ports:
      - "8191:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMINUSERNAME?Variable not set}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMINPASSWORD?Variable not set}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL?Variable not set}
    depends_on:
      - rabota-mongo-dev
    networks:
      - rabota-dev-api-network

  rabota-mongo-test:
    image: mongo
    container_name: rabota-mongo-test
    restart: always
    command: mongod --port 27021
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TEST_ROOT_USERNAME?Variable not set}
      MONGO_INITDB_ROOT_PASSWORD: ${TEST_ROOT_PASSWORD?Variable not set}
      MONGO_INITDB_DATABASE: test-db
    networks:
      - rabota-dev-api-network

  rabota-api:
    ports:
      - "8192:8000"
    env_file: .env
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    depends_on:
      - rabota-mongo-dev
    networks:
      - rabota-dev-api-network

volumes:
  rabota-mongo-dev-data:
    driver: local

networks:
  rabota-dev-api-network:

